version: "3.8"

services:

    app:
        build: .
        ports:
            - 8080:8080
            - 8000:8000
        env_file:
            - ${RTE}.env
        volumes:
            - .:/app/
            - static:/static/
            - media:/media/
        networks:
            - es-net

volumes:
    static:
    media:

networks:
  es-net:
    driver: bridge
